export let actions = {
    FETCH_BOARD: "FETCH_BOARD",
    FETCH_BOARD_SUCCEEDED: "FETCH_BOARD_SUCCEEDED",
    FETCH_BOARD_FAILED: "FETCH_BOARD_FAILED",

    MAKE_MOVE: "MAKE_MOVE",
    MAKE_MOVE_SUCCEEDED: "MAKE_MOVE_SUCCEEDED",
    MAKE_MOVE_FAILED: "MAKE_MOVE_FAILED",

    NEW_GAME: "NEW_GAME",
    NEW_GAME_SUCCEEDED: "NEW_GAME_SUCCEEDED",
    NEW_GAME_FAILED: "NEW_GAME_FAILED",

    RESET_GAME: "RESET_GAME",
    RESET_GAME_SUCCEEDED: "RESET_GAME_SUCCEEDED",
    RESET_GAME_FAILED: "RESET_GAME_FAILED",

    UPDATE_LOG: "UPDATE_LOG",

    FETCH_HISTORY: "FETCH_HISTORY",
    FETCH_HISTORY_SUCCEEDED: "FETCH_HISTORY_SUCCEEDED",
    FETCH_HISTORY_FAILED: "FETCH_HISTORY_FAILED",

    RESET_HISTORY: "RESET_HISTORY",
    RESET_HISTORY_SUCCEEDED: "RESET_HISTORY_SUCCEEDED",
    RESET_HISTORY_FAILED: "RESET_HISTORY_FAILED",

    TOGGLE_MODAL: "TOGGLE_MODAL"
}
